APP_ENV: DEV # DEV,TEST,PROD (DEV and TEST print logs in CMD screen)
LOG_LEVEL: "0"
# panic (zerolog.PanicLevel, 5)
# fatal (zerolog.FatalLevel, 4)
# error (zerolog.ErrorLevel, 3)
# warn (zerolog.WarnLevel, 2)
# info (zerolog.InfoLevel, 1)
# debug (zerolog.DebugLevel, 0)
# trace (zerolog.TraceLevel, -1)
ORCHESTRATORM8:
  Services:
      naabum8: "http://127.0.0.1:8001"
      katanam8: "http://127.0.0.1:8002"
  Exchanges: # Format below: exchange_name:exchange_type
    cptm8: "topic"
    notification: "topic"
  naabum8: # API service name
    Queue:
      - "cptm8" # exchange name
      - "qnaabum8" # queue name
      - 1 # prefetch count
    Routing-keys:
      - "cptm8.naabum8.#" # binding key
    Queue-arguments:
      "x-max-length": 1 # x-queue-type, x-max-length, x-max-length-bytes, x-overflow, x-message-ttl, x-expires, x-max-age, x-stream-max-segment-size-bytes, x-queue-version, x-consumer-timeout, x-single-active-consumer
      "x-overflow": "reject-publish"
    Consumer:
      - "qnaabum8" # queue name
      - "cnaabum8" # consumer name
      - "false" # autoack
    Publisher: # This the default published message
        - "cptm8" # exchange
        - "cptm8.katanam8.get.scan" # Routing key
        - "naabum8" # caller service
NAABUM8: # Naabu scan settings
  Verbose: false
  NoColor: true
  JSON: true
  Silent: 
  Stdin: 
  Verify: 
  Version: 
  Ping: 
  Debug: 
  ExcludeCDN: true
  Nmap: 
  InterfacesList: 
  Retries: 1
  Rate: 1000
  Timeout: 1000
  WarmUpTime: 2
  Host:
  HostsFile:
  Output:
  Ports: "21,23,22,80,443,8080,8443" # add ports to scan
  PortsFile:
  ExcludePorts:
  ExcludeIps:
  ExcludeIpsFile:
  TopPorts:
  PortThreshold:
  SourceIP:
  SourcePort:
  Interface:
  ConfigFile:
  Threads: 25
  EnableProgressBar:
  StatsInterval:
  ScanAllIPS: false
  IPVersion: 
    - 4
  ScanType: s
  NmapCLI: 'nmap -sV -oX ./tmp/nmap-output.xml'
  # Proxy: 'IPAddress:Port'
  Proxy: 
  #ProxyAuth: 'user:pass'
  ProxyAuth:
  Resolvers:
  baseResolvers: 
  OnResult:
  CSV:
  Resume:
  ResumeCfg:
  Stream:
  Passive:
  OutputCDN:
  HealthCheck: 
  OnlyHostDiscovery: 
  SkipHostDiscovery: true
  TcpSynPingProbes:
  TcpAckPingProbes:
  IcmpEchoRequestProbe:
  IcmpTimestampRequestProbe:
  IcmpAddressMaskRequestProbe:
  ArpPing:
  IPv6NeighborDiscoveryPing:
  InputReadTimeout:
  DisableStdin:
  ServiceDiscovery:
  ServiceVersion:
  ReversePTR:
  DisableUpdateCheck:
  MetricsPort:
Database: # PostgreSQL connection details
  location: "hostname"
  port: 5432
  schema: "public"
  database: "databasename"
  username: "dbuser"
  password: "dbpass"
RabbitMQ: # RabbitMQ connection details
  location: "hostname"
  port: 5672
  username: "user"
  password: "pass"
  pool:
    max_connections: # default: 10
    min_connections: # default: 2
    pool.max_idle_time: # default: "1h" Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
    max_lifetime: # default: "2h" Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
    health_check_period: # default: "30m" Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
    connection_timeout: # default: "30s" Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
    retry_attempts: # default: 3
    retry_delay: # default: "2s" Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
